repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_tflint
    - id: terraform_docs
      args:
        - --args=--config=.terraform-docs.yml
